# Generated by Django 5.1.4 on 2025-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_barcode_store_inventoryalert_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='suppllier',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='barcode',
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
