# Import the DefaultRouter Class from Django REST framewwork
# this handles automatic URL routing for ViewSets
from rest_framework.routers import DefaultRouter

# Import the ViewSet classes from views.py file
# These ViewSets handle user registration and login functionality
from .views import UserRegistrationViewSet, UserLoginViewset

# Import Django's URL handling utilities
# path() - Creates individual URL patterns
# include() - Allows including URL patterns from other modules
from django.urls import path, include

# Create a new router instance to automatically handle ViewSet URLs
router = DefaultRouter()


# Register the UserRegistrationViewSet with the router
# - 'register' becomes the URL prefix 
# - basename='user-registration' is used for generating URL names
router.register(r'register', UserRegistrationViewSet, basename='user-registration')

# Register the UserLoginViewSet with the router
# - 'login' becomes the URL prefix 
# - basename='user-login' is used for generating URL names
router.register(r'login', UserLoginViewset, basename='user-login')


#Define the URL patterns for the Django application


urlpatterns = [
    # Include all URLs generated by the router
    # The empty string '' means these URLs will be availabe at the root path
    path('', include(router.urls)),
]
